package View;

import com.sun.istack.internal.logging.Logger;
import java.sql.SQLException;
import java.util.logging.Level;
import sun.util.logging.PlatformLogger;

public class MenuUtama extends javax.swing.JFrame {
    public MenuUtama() {
        initComponents();
        this.setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Master = new javax.swing.JMenu();
        MMotor = new javax.swing.JMenuItem();
        MMekanik = new javax.swing.JMenuItem();
        MService = new javax.swing.JMenuItem();
        MSparepart = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        TWo = new javax.swing.JMenuItem();
        TKwitansiwo = new javax.swing.JMenuItem();
        TPenjualan = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        LService = new javax.swing.JMenuItem();
        LPenjualan = new javax.swing.JMenuItem();
        LPembayaran = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();

        jLabel2.setText("jLabel2");

        jMenuItem1.setText("jMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 2, 11)); // NOI18N
        jLabel18.setText("Jogja Motor Sports");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Billy\\Downloads\\Jadi.png")); // NOI18N

        Home.setText("Home");
        jMenuBar1.add(Home);

        Master.setText("Master");

        MMotor.setText("Entry Data Motor");
        MMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMotorActionPerformed(evt);
            }
        });
        Master.add(MMotor);

        MMekanik.setText("Entry Data Mekanik");
        MMekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMekanikActionPerformed(evt);
            }
        });
        Master.add(MMekanik);

        MService.setText("Entry Data Service");
        MService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MServiceActionPerformed(evt);
            }
        });
        Master.add(MService);

        MSparepart.setText("Entry Data Sparepart");
        MSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSparepartActionPerformed(evt);
            }
        });
        Master.add(MSparepart);

        jMenuBar1.add(Master);

        Transaksi.setText("Transaksi");

        TWo.setText("Cetak Work Order");
        TWo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWoActionPerformed(evt);
            }
        });
        Transaksi.add(TWo);

        TKwitansiwo.setText("Cetak Kwitansi WO");
        TKwitansiwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKwitansiwoActionPerformed(evt);
            }
        });
        Transaksi.add(TKwitansiwo);

        TPenjualan.setText("Cetak Penjualan Sparepart");
        TPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPenjualanActionPerformed(evt);
            }
        });
        Transaksi.add(TPenjualan);

        jMenuBar1.add(Transaksi);

        Laporan.setText("Laporan");

        LService.setText("Laporan Service");
        LService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LServiceActionPerformed(evt);
            }
        });
        Laporan.add(LService);

        LPenjualan.setText("Laporan Penjualan Sparepart");
        LPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPenjualanActionPerformed(evt);
            }
        });
        Laporan.add(LPenjualan);

        LPembayaran.setText("Laporan Pembayaran");
        LPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPembayaranActionPerformed(evt);
            }
        });
        Laporan.add(LPembayaran);

        jMenuBar1.add(Laporan);

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 382, Short.MAX_VALUE)
                .addComponent(jLabel18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(jLabel18))
        );

        setSize(new java.awt.Dimension(503, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMotorActionPerformed
    View.MMotor m = new View.MMotor();
    m.setVisible(true);
    setLocationRelativeTo(this);
    }//GEN-LAST:event_MMotorActionPerformed

    private void LPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPembayaranActionPerformed
        View.LapPembayaran m = new View.LapPembayaran();
        m.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LPembayaranActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void MMekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMekanikActionPerformed
    View.MMekanik m = new View.MMekanik();
    m.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MMekanikActionPerformed

    private void MServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MServiceActionPerformed
        View.MService s = new View.MService();
        s.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MServiceActionPerformed

    private void MSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSparepartActionPerformed
        View.MSparepart s = new View.MSparepart();
        s.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MSparepartActionPerformed

    private void TWoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWoActionPerformed
        try{
        View.TWo w = new View.TWo();
        w.setVisible(true);
        setLocationRelativeTo(this);
        w.getTxtnowo().requestFocus();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TWoActionPerformed

    private void TKwitansiwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKwitansiwoActionPerformed
        View.TKwitansiwo k = new View.TKwitansiwo();
        k.setVisible(true);
        setLocationRelativeTo(this);
        k.getTxtnokwitansi().requestFocus();
    }//GEN-LAST:event_TKwitansiwoActionPerformed

    private void TPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPenjualanActionPerformed
        View.TPenjualan k = new View.TPenjualan();
        k.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_TPenjualanActionPerformed

    private void LServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LServiceActionPerformed
        LapService l = new LapService();
        l.setVisible(true);
        l.setLocationRelativeTo(this);
    }//GEN-LAST:event_LServiceActionPerformed

    private void LPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPenjualanActionPerformed
        LapPenjualanSparepart l = new LapPenjualanSparepart();
        l.setVisible(true);
        l.setLocationRelativeTo(this);
    }//GEN-LAST:event_LPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu Home;
    private javax.swing.JMenuItem LPembayaran;
    private javax.swing.JMenuItem LPenjualan;
    private javax.swing.JMenuItem LService;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem MMekanik;
    private javax.swing.JMenuItem MMotor;
    private javax.swing.JMenuItem MService;
    private javax.swing.JMenuItem MSparepart;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuItem TKwitansiwo;
    private javax.swing.JMenuItem TPenjualan;
    private javax.swing.JMenuItem TWo;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
